### ISSUE TITLE
Hook fails to run

### ISSUE THREAD

**Issue by jasonsims** [Kikobeats/sails-hook-newrelic#1]
The hook is failing to run for me in sails v0.10.5. Is there any additional setup I'm missing? I ran

```
npm install -s sails-hook-newrelic
vim config/newrelic  # added valid config
```

I added a console.log to `index.js` of this lib and it doesn't appear to be called on lift.

**Comment by Kikobeats** [comment]
You need 0.11 version of sails

**Comment by jasonsims** [comment]
Ok cool, thanks for the quick response!
