### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by dlogvinenko** [Kikobeats/sails-hook-newrelic#7]
Hi,

Sails v0.11.0
Node v0.12.2

Doesn't work for me.
What I did:

1) `sudo npm install sails-hook-newrelic --save` (in projects folder)
2) Created newrelic.js config in config/newrelic.js:

``` javascript
module.exports.newrelic = {
    app_name: ['test-app'],
    license_key: 'LICENSE_KEY_ADDED_OF_COURSE',
    logging: {
        level: 'trace', // can be error, warn, info, debug or trace
        rules: {
            ignore: ['^/socket.io/*/xhr-polling']
        }
    }
};
```

3) Changed app.js: 

``` javascript
/**
 * app.js
 *
 * Use `app.js` to run your app without `sails lift`.
 * To start the server, run: `node app.js`.
 *
 * This is handy in situations where the sails CLI is not relevant or useful.
 *
 * For example:
 *   => `node app.js`
 *   => `forever start app.js`
 *   => `node debug app.js`
 *   => `modulus deploy`
 *   => `heroku scale`
 *
 *
 * The same command-line arguments are supported, e.g.:
 * `node app.js --silent --port=80 --prod`
 */
require('sails-hook-newrelic/register');
// Ensure we're in the project directory, so relative paths work as expected
// no matter where we actually lift from.
process.chdir(__dirname);
```

4) Deployed app to Heroku
5) In New Relic I see: `Still waiting for data from application`

**Comment by Kikobeats** [comment]
hmmm I not totally sure because at this moment I haven't a sails app using newrelic in production :_

**Comment by dottodot** [comment]
I'm have the same issue, doesn't seem to work at all. In index.js I've tried `console.log(global.newrelic);` and that returns undefined

It also seems `require('sails-hook-newrelic/register');` doesn't do much as I'd expect the following to show the app name.

```
var config = require(path.resolve('config/newrelic')).newrelic;
console.log(config.app_name);
```

**Comment by Kikobeats** [comment]
It's a little strange because dependency version is locked in `package.json`. I can't do too much more because I'm not using it at this moment. I think that the code is very simple and if you need to use it PR are welcome :-)

**Comment by dottodot** [comment]
Think I'll just use the standard integration method, was only looking to use this as it seemed simpler to setup.
