### ISSUE TITLE
More options in config agent

### ISSUE THREAD

**Issue by davidportella** [Kikobeats/sails-hook-newrelic#8]
I tried adding "ignore_server_configuration" and "custom_insights_events" but these options are being ignored tried the same configuration without the hook and it works, my question is whether to register the agent can add these extra options or just take me the basic

**Comment by andrewoh531** [comment]
Also seems like 'agent_enabled' is not being picked up either; resulting in the new-relic agent running when on local or QA environments.

**Comment by kopylash** [comment]
fixed in 0.3.0
